baseurl = "https://skhan890.github.io/testrepo/"
languageCode = "en-us"
title = "WHAMP"
theme = "hugo-xmin"
googleAnalytics = ""
publishDir = "../docs"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "WHAMP"
    url = ".."
    weight = 1

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [statnet](https://github.com/statnet)"
